---
- name: Instalar Apache2
  apt:
    name: apache2
    state: latest
- name: Habilitar e iniciar el servicio de Apache2
  service:
    name: apache2
    enabled: True
    state: started
- name: Copiar el fichero index.html
  template:
    src:  index.html.j2
    dest: /var/www/html/index.html
  notify: Reiniciar httpd
...